version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - docker build -t container_build_demo .
      - docker tag container_build_demo 959844384370.dkr.ecr.us-west-2.amazonaws.com/container_build_demo
      - docker images 
      - printenv
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 959844384370.dkr.ecr.us-west-2.amazonaws.com/container_build_demo:latest
      - docker push 959844384370.dkr.ecr.us-west-2.amazonaws.com/container_build_demo:$IMAGE_TAG
